### ISSUE TITLE
Range fader doesn't work since 17/11/2023

### ISSUE THREAD

**Issue by Knbi** [nebularg/PitBull4#59]
Straight up refuses to work, no error messages that I saw. Perhaps linked to recent API changes?

**Comment by nebularg** [comment]
Yea, I made a quick fix to remove the protected API usage, but haven't had time to look into it more. Is the range fader set to use class spells?

**Comment by Knbi** [comment]
> Yea, I made a quick fix to remove the protected API usage, but haven't had time to look into it more. Is the range fader set to use class spells? what class are you?

It doesn't work whatsoever, I'm a vengeance DH but it doesn't work on Priest/Warlock either.

**Comment by TreizeEU** [comment]
I'll add my notes here instead of making a new ticket?

I, too, have noticed this issue on several of my alts.

Specs with the problem (tested raids with emerald dream world boss groups):

Death Knight (Frost)
Demon Hunter (Vengeance)
Hunter (BM & Survival)
Warrior (Fury)

I have all classes except monk at lvl 70 to test with.

My raid settings are set to Class Abilities, my party settings are set to Helpful spells (40 yards). I can't remember why I set them up different between party and raids, though.

I hope this is helpful?
